spring:
  application:
    name: bookstore
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false
  flyway:
    locations: migration
  jackson:
    default-property-inclusion: non_null # Remove null values in deserialization
environments:
  secret_key: ${SECRET_KEY:DEFAULT_KEY}