spring:
  profiles:
    active: dev
  application:
    name: bookstore
  config:
    import: optional:file:.env[.properties]
  jackson:
    default-property-inclusion: non_null # Remove null values in deserialization
environments:
  secret_key: ${SECRET_KEY:DEFAULT_KEY}